### ISSUE TITLE
Dub broken for compilers older than 2.084 (std.net.curl does not understand http2)

### ISSUE THREAD

**Issue by ibuclaw** [dlang-community/setup-dlang#29]
I was going to raise a PR with the following patch:
```patch
diff --git a/lib/compiler.js b/lib/compiler.js
index 9daff27..839716c 100644
--- a/lib/compiler.js
+++ b/lib/compiler.js
@@ -73,7 +73,9 @@ function dmd(version) {
             `http://downloads.dlang.org/nightlies/dmd-master/dmd.${version}`
             : beta ? `http://downloads.dlang.org/pre-releases/2.x/${folder}/dmd.${version}`
                 : `http://downloads.dlang.org/releases/2.x/${folder}/dmd.${version}`;
-        const download_dub = minor !== undefined && minor < 72;
+        // Dub versions shipped with dmd older than 2.084 have broken HTTP/2 support.
+        // See: https://github.com/dlang/phobos/pull/6752
+        const download_dub = minor !== undefined && minor < 84;
         switch (process.platform) {
             case "win32": return {
                 name: "dmd",
diff --git a/src/compiler.ts b/src/compiler.ts
index f7f63be..5b11eed 100644
--- a/src/compiler.ts
+++ b/src/compiler.ts
@@ -78,7 +78,9 @@ async function dmd(version: string): Promise<CompilerDescription> {
         : beta ? `http://downloads.dlang.org/pre-releases/2.x/${folder}/dmd.${version}`
             : `http://downloads.dlang.org/releases/2.x/${folder}/dmd.${version}`;
 
-    const download_dub = minor !== undefined && minor < 72;
+    // Dub versions shipped with dmd older than 2.084 have broken HTTP/2 support.
+    // See: https://github.com/dlang/phobos/pull/6752
+    const download_dub = minor !== undefined && minor < 84;
 
     switch (process.platform) {
         case "win32": return {
```

However, looking at the download_dub logic, I see the following comment:
```javascript
export async function legacyDub(): Promise<DubDescription> {
    // download some dub version for legacy compilers not shipping dub
    // this is the last version on the old download page from September 2018
```
The HTTP/2 fix was applied to Phobos in November 2018, so the legacy dub is useless as well.

**Comment by Geod24** [comment]
I thought the registry was not using HTTP/2 because of this ?

**Comment by ibuclaw** [comment]
It seems that someone forgot and switched over to http2 only anyway. I ran into this earlier in the year and had to backport the patch to gcc-10 (gdc is used to build dub on many distros).

**Comment by Geod24** [comment]
The fix happened May 15th: https://github.com/dlang/dub/issues/1928#issuecomment-628798265

**Comment by ibuclaw** [comment]
I myself forgot about it until I ran into it again using 2.081 compiler here.

https://github.com/sociomantic-tsunami/neptune/pull/258

**Comment by Geod24** [comment]
> sociomantic-tsunami/neptune#258

The failure looks completely unrelated to me, this is using Travis, not the Github Action.

**Comment by ibuclaw** [comment]
Look in the actions tab. ;-)

**Comment by ibuclaw** [comment]
> Yeah it's trying to look up https://github.com/sociomantic-tsunami/neptune/blob/v0.x.x/src/internal/dub.sdl on the registry, no wonder it gets a 404

So you think that it's a coincidence that 2.084 works?  Maybe there was another change in dub that fixed a dependency resolver bug?

**Comment by Geod24** [comment]
> So you think that it's a coincidence that 2.084 works? Maybe there was another change in dub that fixed a dependency resolver bug?

Yep I think it's a coincidence. But I don't know how it didn't work before, because 2.084 was released in January 2019, long after those scripts were written. I would just go with the latest version and call it a day.

**Comment by wilzbach** [comment]
If you're on Travis, you can manually opt-in to the latest dub with the little known `dmd-<version>,dub`. It's also possible to specify a specific dub version this way, but by default it should download the latest one.

**Comment by ibuclaw** [comment]
> > So you think that it's a coincidence that 2.084 works? Maybe there was another change in dub that fixed a dependency resolver bug?
> 
> Yep I think it's a coincidence. But I don't know how it didn't work before, because 2.084 was released in January 2019, long after those scripts were written. I would just go with the latest version and call it a day.

I don't think it's the scripts that have changed, but the upstream dependencies.

**Comment by ibuclaw** [comment]
> If you're on Travis, you can manually opt-in to the latest dub with the little known `dmd-<version>,dub`. It's also possible to specify a specific dub version this way, but by default it should download the latest one.

Doesn't seem to work with the actions script.

https://github.com/sociomantic-tsunami/neptune/pull/258/checks?check_run_id=1002789543

**Comment by ibuclaw** [comment]
I'll close this for now then, as the original claim seems to have been fictitious.

Though maybe a new feature request should be opened to allow choosing an alternative version of dub that is not supplied with the compiler (i.e: fetch the latest 1.22 release).

**Comment by wilzbach** [comment]
> Doesn't seem to work with the actions script.
> https://github.com/sociomantic-tsunami/neptune/pull/258/checks?check_run_id=1002789543

Yes, it only works with the installer script which is used by Travis.

**Comment by wilzbach** [comment]
> Though maybe a new feature request should be opened to allow choosing an alternative version of dub that is not supplied with the compiler (i.e: fetch the latest 1.22 release).

https://github.com/dlang-community/setup-dlang/issues/30
