### ISSUE TITLE
Allow installing the specific versions of dub

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/setup-dlang#30]
(from https://github.com/dlang-community/setup-dlang/issues/29)

The install.sh script supports opt-in into newer dub versions as older dub versions historically ran into a lot of problems (dependency resolution, no fallback mirrors, ...). Hence, I think the GitHub Action should provide the same:

- [ ] allow installing the latest version of dub
- [ ] allow installing a specific version of dub

The install script uses the syntax: `<compiler>,<dub>`

See also:
- https://github.com/dlang/installer/blob/3b305b34d2eb79dd420eabec2f0a170d9acde1ac/script/install.sh#L594
- https://github.com/dlang/installer/blob/master/test/t/dub.sh

Note: currently the automatic update of https://dlang.github.io/dub/LATEST seems to be broken. I just pushed the latest tag manually, but we might need to look into this.

**Comment by ibuclaw** [comment]
There's a `download_dub` input parameter. I guess a new dub version parameter could be added, but default to the latest release.
