### ISSUE TITLE
1.0.1 release?

### ISSUE THREAD

**Issue by andre2007** [dlang-community/setup-dlang#31]
Could we have a 1.0.1 release, with the latest changes (https://github.com/dlang-community/setup-dlang/compare/v1.0.0...v1)?

While syncing this repository to a Github Enterprise Server (using https://github.com/actions/actions-sync)
latest release is used instead of master.

**Comment by Geod24** [comment]
Done: https://github.com/dlang-community/setup-dlang/releases/tag/v1.0.1
