### ISSUE TITLE
Deprecated `add-path` and `set-env`

### ISSUE THREAD

**Issue by vladdeSV** [dlang-community/setup-dlang#34]
Running a workflow with this action outputs the following warnings:
> Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

The mentioned GitHub blog post is from the 1st of October, so it is relatively recent.

<details><summary>Relevant raw logs</summary><pre>Adding '/opt/hostedtoolcache/dc/dmd-2.094.1/x64/dmd2/linux/bin64' to path
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Adding '/opt/hostedtoolcache/dc/dmd-2.094.1/x64/dmd2/linux/lib64' to library path
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Done</pre></details>

**Comment by vladdeSV** [comment]
I used version `mihails-strasuns/setup-dlang@v1.0.2`.

**Comment by mihails-strasuns** [comment]
Can you please try the current v1 branch head? It should have been fixed with node module update, I'll make a 1.0.3 if that is indeed the case.

**Comment by vladdeSV** [comment]
@mihails-strasuns That did the job. Using `dlang-community/setup-dlang@v1` gives no warnings.

<details><summary>Relevant raw logs</summary><pre>Adding '/opt/hostedtoolcache/dc/dmd-2.094.1/x64/dmd2/linux/bin64' to path
Adding '/opt/hostedtoolcache/dc/dmd-2.094.1/x64/dmd2/linux/lib64' to library path
Done</pre></details>

**Comment by mihails-strasuns** [comment]
Thanks for checking! I'll release 1.0.3 in a moment

**Comment by mihails-strasuns** [comment]
https://github.com/dlang-community/setup-dlang/releases/tag/v1.0.3
