### ISSUE TITLE
Github test workflow is broken!

### ISSUE THREAD

**Issue by ludo456** [dlang-community/setup-dlang#36]
I am using the D workflow called d.yml. It broke very recently. The error seems to follow an upgrade in the github actions framework, [as described here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

**Here is the error:**
![Screenshot from 2021-01-02 20-14-17](https://user-images.githubusercontent.com/28017530/103464858-44ef3700-4d37-11eb-851f-ef49bca3ae43.png)

**The complete log of the error:**
Error: Unable to process command '::add-path::/opt/hostedtoolcache/dc/dmd-2.094.2/x64/dmd2/linux/bin64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=DC::dmd' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Adding '/opt/hostedtoolcache/dc/dmd-2.094.2/x64/dmd2/linux/lib64' to library path
Error: Unable to process command '::set-env name=LD_LIBRARY_PATH::/opt/hostedtoolcache/dc/dmd-2.094.2/x64/dmd2/linux/lib64' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by Geod24** [comment]
Sorry for that. You need to change the reference from `dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7` to `dlang-community/setup-dlang@v1`.

I raised a PR to Github but they are not reviewing it... https://github.com/actions/starter-workflows/pull/709

**Comment by ludo456** [comment]
> You need to change the reference from `dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7` to `dlang-community/setup-dlang@v1`

Thanks, working like a charm now :)
