### ISSUE TITLE
Failed to load curl, tried "libcurl.dll", "curl.dll".

### ISSUE THREAD

**Issue by CyberShadow** [dlang-community/setup-dlang#47]
Seems like there is something missing on Windows, and the `libcurl.dll`, which is included in DMD Windows ZIP files, cannot be loaded.

Example failed run:
https://github.com/CyberShadow/ae/runs/3010103173#step:5:18

The commit:
https://github.com/CyberShadow/ae/commit/37fd2b45f0469a4f23f06b00b50762c4c1529a8a

~~In the same commit, you can find the AppVeyor script [which does work](https://ci.appveyor.com/project/CyberShadow/ae/builds/39887753).~~ (Oops, the AppVeyor script did not test the part which uses cURL.)

**Comment by mihails-strasuns** [comment]
Where is it located? setup-dlang adds these paths for Windows (from the log of the linked job):

```
Adding 'C:\hostedtoolcache\windows\dc\dmd-2.082.1\x64\dmd2\windows\bin' to path
Adding 'C:\hostedtoolcache\windows\dc\dmd-2.082.1\x64\dmd2\windows\lib64' to library path
```

**Comment by CyberShadow** [comment]
There is a `libcurl.dll` in the `windows/bin` and `windows/bin64` directories of the DMD Windows zip files.

**Comment by WebFreak001** [comment]
might just be missing the windows/bin64 folder then?

**Comment by mihails-strasuns** [comment]
See the linked PR.

**Comment by CyberShadow** [comment]
Thank you!

**Comment by alp2344** [comment]
Hi Guys,
 I need a kind support for below issue. 
I can not clone anything  and Jira always showed me this error message 
failed to load library 'libcurl-4.dll'

Could you please support me about this?
My PC 64bit and I m using Windows 11

**Comment by Geod24** [comment]
I don't think your issue is related to this, as this project has nothing to do with Jira. I suggest to look for a Jira-specific support board.

**Comment by Burcuaygun-aygun** [comment]
Hi Guys again
I need a kind support for below issue.
I can not clone anything and Java and Intelij 
always showed me this error message
failed to load library 'libcurl-4.dll'

Could you please support me about this?
My PC 64bit and I m using Windows 11

**Comment by Burcuaygun-aygun** [comment]
Hi Guys again
I need a kind support for below issue.
I can not clone anything and Java and Intelij
always showed me this error message
failed to load library 'libcurl-4.dll'

Could you please support me about this?
My PC 64bit and I m using Windows 11

**Comment by Burcuaygun-aygun** [comment]
> I don't think your issue is related to this, as this project has nothing to do with Jira. I suggest to look for a Jira-specific support board.

Hi Guys again
I need a kind support for below issue.
I can not clone anything and Java and Intelij
always showed me this error message
failed to load library 'libcurl-4.dll'

Could you please support me about this?
My PC 64bit and I m using Windows 11

**Comment by CyberShadow** [comment]
This project doesn't have anything to do with Java or IntelliJ either, sorry.

**Comment by CyberShadow** [comment]
There is a related problem with LDC on x86. LDC has `libcurl.dll` in three locations: `bin`, `lib32`, and `lib64`. For x86 builds, the one in `lib32` has to be in front in `PATH`.

My workaround: https://github.com/cybershadow/ae/commit/0c4aabe42f174fa66dc1516db42eae39cd97990c

I'm not sure how this could be fixed here; we may need to add an `arch` parameter or such.
