### ISSUE TITLE
actions should now be using node20

### ISSUE THREAD

**Issue by SingingBush** [dlang-community/setup-dlang#68]
When using `setup-dlang@v1` it's currently using node16. Based on the [runs for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) documentation and looking at source for `actions/checkout@v4` it appears node20 is now the way to go. Perhaps if this is updated then it should be as a v2 tag

**Comment by Geod24** [comment]
Done in #74. thanks for reporting.

**Comment by SingingBush** [comment]
There needs to be new tag for users to get the update. Any chance of getting a 1.4.0 release?

**Comment by PetarKirov** [comment]
@SingingBush Done: https://github.com/dlang-community/setup-dlang/releases/tag/v1.4.0
